### PR TITLE
Add simple debouncer

### PR DESCRIPTION
**Pull request by ognjen-petrovic**
Here it is, simple one, that just counts update events.
Threshold is hardcoded to 10 and certainly should be OK to move it to settings.

### CODE REVIEW

**Comment by xy2z** [comment]
I'd prefer a timer instead of a counter..
and no confirm(), the user should not be annoyed with comfirms. Just save the content when changing note.

**Comment by xy2z** [comment]
Thanks! Just a few stuff and I think it's done 👍 
- Can you rename `is_dirty` to `note_changed`
- Can you add a `window.onbeforeunload` function, and if `this.note_changed` then the user must confirm leaving the page without saving. Something like "Are you sure you want to leave without saving?"

**Comment by ognjen-petrovic** [comment]
1. Yes
2. If user says No, what we do ... save and leave?

**Comment by xy2z** [comment]
2. I dont think the browser lets us do anything, if user says no.
 But if we can, then yes, save before leave

**Comment by ognjen-petrovic** [comment]
There is [sendBeacon](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) that works in event listener. 

So maybe, if browser supports sendBeacon just silently save, otherwise prompt. Something like:

```
window.addEventListener('beforeunload', (e) => {
  if (is_dirty) {
    if (navigator.sendBeacon) {
        navigator.sendBeacon('url', 'data');
    }
    else {
        e.preventDefault();
        e.returnValue = '';        
    }
  }
});
```

And what about Codacy, it says: Identifier 'is_dirty' is not in camel case?

**Comment by xy2z** [comment]
Cool, didn't know about sendBeacon, but a quick search shows it may not be easy with CSRF.
IMO you can just implement it without sendBeacon, and we can make an issue for sendBeacon later.

So just add a confirm if note is not saved.

And don't mind Codacy, I haven't set it up probably yet.

**Comment by xy2z** [comment]
Thanks

**Pull request merged**
