### PR TITLE
Feature social login

### PR DESCRIPTION
**Pull request by MJunaidAhmad**

### CODE REVIEW

**Comment by xy2z** [comment]
Awesome! The code looks much better now 😄 
I'll test it out tomorrow.

**Comment by xy2z** [comment]
After testing Twitter:

- Error message is not pretty, can you put it inside the login box, above the "Login" h1?
And only show the error, if it's not already shown in the email/password login?

- All oauth logins buttons are visible, even though I haven't set any env variables.
Use `@if (!empty(config()->get('services.facebook.client_id')))` instead of `config()->has()`

- I can only click on the buttons if I click on the text, not the rest of the button.
Remove the `<button>` and instead use `<a class="button is-fullwidth is-info"`
then `style="color:white;"` is not needed any longer.

- Email column should be `nullable`, since we don't really need it when for oauth users.
Twitter for example, requires special permission to get the email, so it gives an error on login.

**Comment by MJunaidAhmad** [comment]
Got it. (y)

**Comment by xy2z** [comment]
Thanks! 👍 
I have tested with twitter and it works. I will test with Google and Facebook later this week, but should work fine, so I'm merging :)

**Pull request merged**
